name: Bug report
description: Create a report to help us improve
title: "Bug report: "
labels:
  - "Type: bug"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a new issue!


        Please remember that you should fill out all files marked with a `*` and that you should give as much information as possible."
      preview_only: false
  - type: checkboxes
    attributes:
      value: "Make sure you have performed these important steps before opening this issue"
      options:
        - label: "I [searched the issues page](https://github.com/Welcome-Bot/welcome-bot/issues?q=is%3Aissue) for already existing bug reports."
          required: true
      label: Checks
  - type: textarea
    attributes:
      label: Description
      description: "Try to describe the bug as detailed as possible.\nUse the below text fields for reproduction steps."
      placeholder: I used the ... command & the bot did ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Server id
      description: Please share your server id
    validations:
      required: true
