name: CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development, v2]
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "14.x"
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test

  build:
    name: Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8b842e721d38d18bea23b57f4c040e53331f4ca2
        with:
          images: puneetgopinath/discord_welcome-bot
      - name: Build and push Docker image
        uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
