# https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16.x"
      - run: npm install npm -g
      - run: npm install
      #- run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - run: npm install npm -g
      - run: npm install
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  #publish-gpr:
  #needs: build
  #runs-on: ubuntu-latest
  #permissions:
  #contents: read
  #packages: write
  #steps:
  #- uses: actions/checkout@v2
  #- uses: actions/setup-node@v3.4.1
  #with:
  #node-version: 12
  #registry-url: https://npm.pkg.github.com/
  #scope: "@Welcome-Bot"
  #- run: npm install
  #- run: npm publish
  #env:
  #NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
